### ISSUE TITLE
`OfflineRecognizerResult` missing tokens, timestamps, lang, emotion, event

### ISSUE THREAD

**Issue by eschmidbauer** [k2-fsa/sherpa-onnx-go#4]
Hello! Thank you for sharing this go project. 
I have noticed that the bindings may not be current. For example, the `OfflineRecognizerResult` is missing several fields  (`Tokens []string, Timestamps []float32, Lang string, Emotion string, Event string`)
Would it be possible to add these to the go bindings?

**Comment by csukuangfj** [comment]
would you like to contribute?

**Comment by eschmidbauer** [comment]
yes, unfortunately i was not able to figure out how to convert the tokens or timestamps
```tokens *_Ctype_char -> Tokens []string```
```timestamps *_Ctype_float-> Timestamps []float32```

![image](https://github.com/user-attachments/assets/65565d58-fd6a-4b36-990a-3879b840cf5a)



If you could give me some info on converting those two datatypes, i'd be happy to write the code

**Comment by csukuangfj** [comment]
> unfortunately i was not able to figure out how to convert the tokens or timestamps

Please have a look at
https://github.com/k2-fsa/sherpa-onnx/blob/e34a1a2aa39f1cf8384e1bf327e7edd849dbe739/scripts/go/sherpa_onnx.go#L707-L716

A second example is given below (untested, please test it by yourself)
```go

n := int(p.count);
result.Timestamps = make([]float32, n);
timestamps := (*[1<<28]C.float)(unsafe.Pointer(p.timestamps))[:n:n];
for i := 0; i < n; i++ {
  result.Timestamps[i] = c.float(timestamps[i]);
}
```

**Comment by csukuangfj** [comment]
Here is the code for processing tokens. Please see also
https://github.com/k2-fsa/sherpa-onnx/blob/e34a1a2aa39f1cf8384e1bf327e7edd849dbe739/scripts/go/sherpa_onnx.go#L1114-L1121

```go
n := int(p.count);

result.Tokens = make([]string, n);
tokens := (*[1<<28]*C.char)(unsafe.Pointer(p.tokens_arr))[:n:n];

for i := 0; i < n; i++ {
  result.Tokens[i] = G.GoString(tokens[i]);
}
```

**Comment by eschmidbauer** [comment]
opened PRs:
 - https://github.com/k2-fsa/sherpa-onnx-go-macos/pull/4

 - https://github.com/k2-fsa/sherpa-onnx-go-linux/pull/4

 - https://github.com/k2-fsa/sherpa-onnx-go-windows/pull/3

**Comment by csukuangfj** [comment]
Could you close them and change the following file instead?

https://github.com/k2-fsa/sherpa-onnx/blob/master/scripts%2Fgo%2Fsherpa_onnx.go

**Comment by eschmidbauer** [comment]
all set
See new PR [here](https://github.com/k2-fsa/sherpa-onnx/pull/1277)
